"""
Deterministic offline LLM backend for tests and no-model demos.

Mirrors the contract the old test suite exercised by monkeypatching
app.llm.chat: canned conversational replies plus valid SecurityReport JSON
when a JSON-mode analysis call is detected. Never touches the network.
"""
import asyncio
import json
from typing import List, Dict

_FAKE_REPORT = {
    "title": "Stub Security Assessment",
    "client_context": "Placeholder report generated by the offline stub backend.",
    "scope": "All uploaded documents.",
    "executive_summary": "Stub backend active: no real model is loaded, so this report contains placeholder findings to exercise the pipeline.",
    "findings": [
        {
            "title": "Stub finding: verify with a real model",
            "severity": "Medium",
            "description": "The stub backend always returns this finding so that report rendering can be exercised without a model.",
            "evidence": "n/a (stub backend)",
            "source_file": None,
            "framework": "NIST_CSF",
            "control_id": "PR.PS",
            "remediation": "Load a real Qwen3.5 GGUF via the model picker and regenerate.",
        }
    ],
    "overall_risk_rating": "Medium",
    "recommendations_summary": ["Load a real model tier from the model picker"],
    "diagram": "flowchart LR\n    Internet[\"Internet\"] --> FW[\"Perimeter Firewall\"]\n    FW --> Web[\"Web Server\"]\n    Web --> DB[(\"Customer Database\")]",
}


def _looks_like_map_prompt(messages: List[Dict[str, str]]) -> bool:
    system = messages[0].get("content", "") if messages else ""
    return "ONE batch of excerpts" in system


def _looks_like_reduce_prompt(messages: List[Dict[str, str]]) -> bool:
    system = messages[0].get("content", "") if messages else ""
    return "already reviewed a client's full document set" in system


def _last_user_text(messages: List[Dict[str, str]]) -> str:
    for m in reversed(messages):
        if m.get("role") == "user":
            return m.get("content", "")
    return ""


_STUB_DIAGRAM_REPLY = (
    "Here is the stub network architecture:\n\n"
    "```mermaid\n"
    "flowchart LR\n"
    "    Internet[\"Internet\"] --> FW[\"Perimeter Firewall\"]\n"
    "    FW --> Web[\"Web Server\"]\n"
    "    FW --> Admin[\"Admin Workstation\"]\n"
    "    Web --> DB[(\"Customer Database\")]\n"
    "```\n"
    "The perimeter firewall separates the internet-facing web server from the internal database."
)

_STUB_TABLE_REPLY = (
    "| Host | Exposure | Severity |\n"
    "|---|---|---|\n"
    "| web-01 | Internet-facing | High |\n"
    "| db-01 | Internal only | Medium |\n"
    "| admin-ws | VPN only | Low |"
)


def _looks_like_diagram_request(messages: List[Dict[str, str]]) -> bool:
    text = _last_user_text(messages)
    return "exactly ONE mermaid code block" in text or "mermaid block was not valid" in text


def _looks_like_table_request(messages: List[Dict[str, str]]) -> bool:
    text = _last_user_text(messages)
    return "GitHub-flavored" in text or "well-formed markdown table" in text


async def chat(
    messages: List[Dict[str, str]],
    temperature: float = 0.2,
    json_mode: bool = False,
    max_tokens: int | None = None,
) -> str:
    import json as _json

    if _looks_like_map_prompt(messages) or _looks_like_reduce_prompt(messages) or json_mode:
        return _json.dumps(_FAKE_REPORT)
    if _looks_like_diagram_request(messages):
        return "**STUB MODE ACTIVE** — not a real model response.\n\n" + _STUB_DIAGRAM_REPLY
    if _looks_like_table_request(messages):
        return "**STUB MODE ACTIVE** — not a real model response.\n\n" + _STUB_TABLE_REPLY
    return "This is a stub conversational reply from Fortis (no model loaded)."


async def chat_stream(messages: List[Dict[str, str]], temperature: float = 0.2):
    text = await chat(messages)
    for word in text.split(" "):
        yield word + " "
        await asyncio.sleep(0)
